### ISSUE TITLE
Remove the Collection Class, replace with List

### ISSUE THREAD

**Issue by benhar-dev** [Mobject-Dev-Team/mobject-collections#11]
CollectionChangedEvent
CollectionDisposedEvent

**Comment by piratecarrot** [comment]
Should Collection even exist? It just wraps a LinkedList. Since LinkedList implements the I_Collection interface it can be passed where an I_Collection is requested.

**Comment by benhar-dev** [comment]
Originally the Collection class was made for people who did not have a requirement for what type of collection they needed.  However I think you are correct. Also with the pending addition of @maxxie85 list class then this class can be removed and the I_Collection will remain.

**Comment by benhar-dev** [comment]
Collection class has been removed in v0.6.0
