### ISSUE TITLE
v0.6.0-pending

### ISSUE THREAD

**Issue by benhar-dev** [Mobject-Dev-Team/mobject-collections#12]
TODO list before releasing v0.6.0

- [x] Update revision history
- [x] Review documentation for changes
- [x] Update library version in project
- [x] Link test project to new version
- [x] Merge branch to main and close this issue

**Comment by piratecarrot** [comment]
Should Collection even exist? It just wraps a LinkedList. Since I_LinkedList implements the I_Collection interface it can be passed where an I_Collection is requested.
