### ISSUE TITLE
Change counts and index to use DINT rather than ULINT

### ISSUE THREAD

**Issue by piratecarrot** [Mobject-Dev-Team/mobject-collections#13]
Consider using UXINT datatype with dealing with items properties such as Count. This ensures it is easily addressable by the target CPU, as ULINT will be non-optimal on 32bit architectures.

**Comment by benhar-dev** [comment]
The collections lib is closely related to the .NET collections so I'll look to change these to DINT.  This follows .NET using the Int32 structure.

**Comment by benhar-dev** [comment]
complete in v0.7.0

**Comment by piratecarrot** [comment]
Just had a thought on this issue, perhaps creating a new DUT called CollectionIndex, which has the bounds (0..whatever), to prevent negative indices. You could also have CollectionSize which would be (1..whatever). This would prevent 0 sized collections.

.NET uses Int32 apparently, because of the common language runtime and has to accommodate languages which are targeting the CLR but don't have unsigned types.
