### ISSUE TITLE
List Implementation

### ISSUE THREAD

**Issue by maxxie85** [Mobject-Dev-Team/mobject-collections#5]
Hi, I have Mobject on my radar for a while and adapted the collection, enumerable ideas into my own core library. 
I have a List implementation, and saw that you guys also are looking to creating a List implementation. 

In the mindset of giving back to OpenSource I would be willing to make a PR that implements my List adaptation. Would you be open for that?

**Comment by benhar-dev** [comment]
Hi @maxxie85 that would be great!

I'm pleased that you have found Mobject to be useful.  It was one of the goals of Mobject to be a community project so we're always happy for people to do PRs.

I'm looking forward to seeing what you have done.

**Comment by benhar-dev** [comment]
Hi @maxxie85, I'll close this issue down, but please feel free to raise the PR with your list implementation.  We have v0.6.0 almost ready to go which has a single breaking change (worth noting, but may not affect you).  This is .Get() is now .TryGet() on the linked list nodes.
